version: 0.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu1804
configuration: 
  - Release
platform:
  - x64
  - x86
cache: src/packages -> **\src\packages.config
install:
  - cd src
  - nuget restore
environment:
  out: $(configuration)\*.dll
build:
   project: src/ts3_channel_watcher.sln
   verbosity: Minimal
for:	
  - matrix:	
      only:	
        - image: Ubuntu1804	
          platform: x64	
    environment:
      out: ChannelWatcher_x64.so
    build_script:	
        - echo "ubuntu x64"
        - sh: gcc -m64 -I../include -c -O2 -Wall -fPIC -DLINUX plugin.cpp	
        - sh: gcc -m64 -o x64/ChannelWatcher_x64.so -shared plugin.o
  - matrix:	
      only:	
        - image: Ubuntu1804	
          platform: x86	
    environment:
      out: ChannelWatcher_x86.so
    build_script:	
        - echo "ubuntu x86"
        - sh: gcc -m32 -I../include -c -O2 -Wall -fPIC -DLINUX plugin.cpp	
        - sh: gcc -m32 -o x86/ChannelWatcher_x86.so -shared plugin.o
artifacts:
  - path: $(out)
    name: $(platform)
    type: zip
deploy:
- provider: GitHub
  auth_token:
    secure: FZBIu3XD5T46oC/YMAi6gJlr5Gye4XLHNJgdBB1l3WM7uf3inuf0LgtTvjdEE3fn
  repository: nimradium/ts3_channel_watcher_test_release
