version: 0.0.{build}
image:
  - Visual Studio 2019
configuration: 
  - Release
platform:
  - x64
cache: src/packages -> **\src\packages.config
install:
  - cd src
  - nuget restore
build:
  project: src/ts3_channel_watcher.sln
  verbosity: Detailed
deploy:
- provider: GitHub
  auth_token:
    secure: FZBIu3XD5T46oC/YMAi6gJlr5Gye4XLHNJgdBB1l3WM7uf3inuf0LgtTvjdEE3fn
  repository: nimradium/ts3_channel_watcher_test_release
